import turtle
exit = turtle.Screen()
bob = turtle.Turtle()
bob.shape("turtle")
bob.color('black')
bob.speed(4)
screen = turtle.Screen()
for i in range(12):
    bob.up()
    bob.right(30)
    bob.forward(100)
    bob.down()
    bob.forward(20)
    bob.up()
    bob.forward(15)
    bob.stamp()
    bob.goto(0,0)
bob.hideturtle()
screen.exitonclick()