import turtle
bob = turtle.Turtle()
bob.pensize(5)
screen = turtle.Screen()
for i in range(3):
    bob.forward(200)
    bob.left(120)
bob.forward(100)
bob.left(120)
bob.forward(100)
bob.right(120)
bob.forward(100)
bob.right(120)
bob.fd(100)
bob.hideturtle()
screen.exitonclick()